templates:
  .default: &default
    missingFileHandler: Info
    values:
      # Apps
      - apps/*.*
      # Env
      - envs/{{ .Environment.Name }}/*.*
      # Values
      - envs/{{ .Environment.Name }}/values/*.*
    secrets:
      # Secrets
      - envs/{{ .Environment.Name }}/secrets/*.*

environments:
  clusters/k0s:
    <<: *default
  client-a/prod:
    <<: *default
  client-b/prod:
    <<: *default
  client-c/prod:
    <<: *default
