releases:
{{- range $release, $v := .Values.apps }}
- name: {{ $release }}
  labels:
    app: {{ $release }}
  chart: {{ $v.repo }}/{{ $v.chart }}
  {{- if $v | getOrNil "version" }}
  version: {{ $v.version }}
  {{- end }}
  missingFileHandler: Info
  values:
    {{- if $v | getOrNil "valueFiles" }}
    {{- range $valueFile := $v.valueFiles }}
    - releases/{{ $valueFile }}
    {{- end }}
    {{- else }}
    - releases/{{ $release }}.yaml.gotmpl
    {{- end }}
    - releases/_override.yaml.gotmpl
  {{- if ($v | getOrNil "installed") }}
  installed: true
  {{- else }}
  installed: false
  {{- end }}
  {{- if ($v | getOrNil "needs") }}
  needs:
    {{- toYaml $v.needs | trim | nindent 4 }}
  {{- end }}
{{- end }}
